### ISSUE TITLE
Is there a way to preview uploadED images?

### ISSUE THREAD

**Issue by oldcastlehq** [VReactor/vr-file-upload-preview#1]
Hey,

Very nice plugin!

I'm only missing one feature. The ability to automatically displayed images on page load. For example:
I want to preview uploadED images. This is a common request from a CRUD system perspective. So, when I edit a product page, I would like to see the preview of all the updated images. So, the user decides what to do with those images. Generally, other plugins would have an option where I can pass an array of images to the plugin to display. 

Is that possible now?

**Comment by VReactor** [comment]
@oldcastlehq Hey, I added a feature in version 1.1.0 and added an example to the [demo](https://vreactor.github.io/vr-file-upload-preview/). Besides I updated the documentation.
